translate("a", "4").
translate("b", "b").
translate("c", "<").
translate("c", "k").
translate("d", "|>").
translate("e", "3").
translate("f", "ph").
translate("g", "g").
translate("g", "9").
translate("h", "h").
translate("i", "1").
translate("j", "j").
translate("k", "|").
translate("l", "1").
translate("m", "/\\/\\").
translate("n", "/\\/").
translate("o", "0").
translate("p", "p").
translate("q", "q").
translate("r", "r").
translate("s", "5").
translate("t", "7").
translate("t", "+").
translate("u", "u").
translate("v", "v").
translate("w", "\\/\\/").
translate("x", "x").
translate("y", "y").
translate("z", "z").
translate(" ", " ").
translate(".", ".").
translate("!", "!").
translate("?", "?").
translate("-", "-").
translate(";", ";").
translate(":", ":").
translate(",", ",").